ENV["CURRENT_SEASON"]    	= "2016"
ENV["CURRENT_ROUND"]     	= "35"
ENV["NUM_ROUNDS"]			= "34"
ENV["API_URL"]				= "http://estadisticas-back.herokuapp.com/api/v1/"
ENV["BACK_URL"]			    = "http://estadisticas-back.herokuapp.com/"
ENV["FRONT_URL"]			= "http://localhost:3000/"