# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8519e9d5fececfabde80eec438871b238dad31e69d7bbc4037489271ceafee80b89589d51723aeeb9fedd89392eb58bcf3ef8aa73507e986f805b1918e8730d7

test:
  secret_key_base: 24628c17bf38881d33675020ac3e56f4d0ab67fab1c47838b78fd2c87adb2efacb5e79f6e7cafbf0c0f5f11812ad57597f7b632ff0f6e8069d5a1cf200b5ee10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
